import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { Icons } from '../components/Icons';
import { Modal } from '../components/Modal';
import { CommentThread } from '../components/CommentThread';
import { useAppContext } from '../context/AppContext';
import { useCollaboration } from '../context/CollaborationContext';
import { useFeedback } from '../context/FeedbackContext';
import { getPollResults, getTaskDashboard } from '../features/collaboration/selectors';
import { useStoredOption } from '../hooks/useStoredOption';
import { formatLocalDateTime } from '../utils/date';
import type { TripTask, TripTaskStatus } from '../domain/models';

const TABS = ['tasks', 'polls', 'notifications'] as const;
const TASK_VIEWS = ['list', 'board'] as const;

export function TripCollaboration() {
  const { id: tripId = '' } = useParams();
  const { trips, currentUserProfile, activities, savedPlaces } = useAppContext();
  const collaboration = useCollaboration();
  const { showToast, confirm } = useFeedback();
  const [tab, setTab] = useStoredOption('bunbietbay-collaboration-tab', TABS, 'tasks');
  const [taskView, setTaskView] = useStoredOption('bunbietbay-task-view', TASK_VIEWS, 'list');
  const [taskFilter, setTaskFilter] = useState('all');
  const [query, setQuery] = useState('');
  const [isTaskOpen, setIsTaskOpen] = useState(false);
  const [isPollOpen, setIsPollOpen] = useState(false);
  const [editingTask, setEditingTask] = useState<TripTask>();
  const trip = trips.find((item) => item.id === tripId);
  if (!trip) return <p>Không tìm thấy chuyến đi.</p>;
  const permissions = collaboration.getPermissions(tripId);
  const tasks = collaboration.tasks.filter((item) => item.tripId === tripId);
  const polls = collaboration.polls.filter((item) => item.tripId === tripId);
  const options = collaboration.pollOptions.filter((item) => item.tripId === tripId);
  const votes = collaboration.pollVotes.filter((item) => item.tripId === tripId);
  const dashboard = getTaskDashboard(tasks, currentUserProfile?.id);
  const filteredTasks = tasks.filter((task) => (taskFilter === 'all' || taskFilter === 'mine' && task.assigneeId === currentUserProfile?.id || taskFilter === 'overdue' && dashboard.overdue.some((item) => item.id === task.id) || task.status === taskFilter) && (!query.trim() || `${task.title} ${task.description ?? ''}`.toLocaleLowerCase('vi').includes(query.trim().toLocaleLowerCase('vi'))));
  const notifications = collaboration.notifications.filter((item) => item.tripId === tripId);

  const run = async (action: () => Promise<void>, success: string) => {
    try { await action(); showToast({ tone: 'success', title: success }); return true; }
    catch (error) { showToast({ tone: 'error', title: 'Không thể cập nhật', message: error instanceof Error ? error.message : 'Hãy thử lại.' }); return false; }
  };

  return <div className="mx-auto max-w-6xl pb-16">
    <header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-secondary">{trip.title}</p><h1 className="font-headline text-3xl font-extrabold">Cộng tác</h1><p className="mt-2 text-sm text-secondary">Công việc, quyết định và cập nhật của cả nhóm tại một nơi.</p></div><div className="flex gap-2">{tab === 'tasks' && permissions.canCreateTasks && <button type="button" onClick={() => setIsTaskOpen(true)} className="min-h-11 rounded-xl bg-primary px-4 font-bold text-on-primary">Thêm nhiệm vụ</button>}{tab === 'polls' && permissions.canCreatePolls && <button type="button" onClick={() => setIsPollOpen(true)} className="min-h-11 rounded-xl bg-primary px-4 font-bold text-on-primary">Tạo bình chọn</button>}</div></header>
    <div role="tablist" aria-label="Cộng tác" className="mb-5 flex overflow-x-auto rounded-xl bg-surface-container-low p-1">{([['tasks','Công việc'],['polls','Bình chọn'],['notifications','Thông báo']] as const).map(([value,label]) => <button key={value} role="tab" aria-selected={tab === value} onClick={() => setTab(value)} className={`min-h-11 flex-1 rounded-lg px-4 text-sm font-bold ${tab === value ? 'bg-surface text-primary shadow-sm' : 'text-secondary'}`}>{label}{value === 'notifications' && notifications.some((item) => !item.readAt) ? ` (${notifications.filter((item) => !item.readAt).length})` : ''}</button>)}</div>

    {tab === 'tasks' && <section><div className="mb-4 grid gap-3 sm:grid-cols-[1fr_auto_auto]"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm nhiệm vụ…" aria-label="Tìm nhiệm vụ" className="min-h-11 rounded-xl border border-outline-variant bg-surface px-3" /><select value={taskFilter} onChange={(event) => setTaskFilter(event.target.value)} aria-label="Lọc nhiệm vụ" className="min-h-11 rounded-xl border border-outline-variant bg-surface px-3"><option value="all">Tất cả ({tasks.length})</option><option value="mine">Việc của tôi ({dashboard.mine.length})</option><option value="overdue">Quá hạn ({dashboard.overdue.length})</option><option value="todo">Cần làm</option><option value="in_progress">Đang làm</option><option value="done">Hoàn thành</option></select><div className="flex rounded-xl bg-surface-container-low p-1"><button type="button" aria-label="Xem danh sách" aria-pressed={taskView === 'list'} onClick={() => setTaskView('list')} className={`size-10 rounded-lg ${taskView === 'list' ? 'bg-surface text-primary' : ''}`}><Icons.List className="mx-auto size-4" /></button><button type="button" aria-label="Xem bảng" aria-pressed={taskView === 'board'} onClick={() => setTaskView('board')} className={`size-10 rounded-lg ${taskView === 'board' ? 'bg-surface text-primary' : ''}`}><Icons.LayoutDashboard className="mx-auto size-4" /></button></div></div>
      <div className={taskView === 'board' ? 'grid gap-4 lg:grid-cols-3' : 'space-y-3'}>{taskView === 'board' ? (['todo','in_progress','done'] as TripTaskStatus[]).map((status) => <TaskColumn key={status} status={status} tasks={filteredTasks.filter((task) => task.status === status)} trip={trip} collaboration={collaboration} currentUserId={currentUserProfile?.id} run={run} confirm={confirm} onEditTask={setEditingTask} />) : filteredTasks.map((task) => <TaskCard key={task.id} task={task} trip={trip} collaboration={collaboration} currentUserId={currentUserProfile?.id} run={run} confirm={confirm} onEditTask={setEditingTask} />)}</div>
      {filteredTasks.length === 0 && <Empty icon={<Icons.CheckSquare className="size-8" />} title="Chưa có nhiệm vụ phù hợp" text="Tạo nhiệm vụ hoặc thay đổi bộ lọc để bắt đầu." />}
    </section>}

    {tab === 'polls' && <section className="space-y-4">{polls.map((poll) => {
      const pollOptions = options.filter((item) => item.pollId === poll.id);
      const pollVotes = votes.filter((item) => item.pollId === poll.id);
      const results = getPollResults(pollOptions, pollVotes);
      const ownVotes = new Set(pollVotes.filter((item) => item.userId === currentUserProfile?.id).map((item) => item.optionId));
      const expired = Boolean(poll.deadline && Date.parse(poll.deadline) <= Date.now());
      const canDelete = trip.permissions.canManageTrip || poll.createdBy === currentUserProfile?.id && pollVotes.length === 0;
      return <article key={poll.id} className="rounded-2xl border border-outline-variant/50 bg-surface-container-lowest p-5">
        <div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary">{poll.selectionMode === 'single' ? 'Chọn một' : 'Chọn nhiều'}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${poll.status === 'open' && !expired ? 'bg-emerald-100 text-emerald-800' : 'bg-surface-container text-secondary'}`}>{poll.status === 'open' && !expired ? 'Đang mở' : expired ? 'Đã hết hạn' : 'Đã đóng'}</span></div><h2 className="mt-3 font-headline text-xl font-bold">{poll.question}</h2>{poll.deadline && <p className="mt-1 text-xs text-secondary">Hạn {formatLocalDateTime(poll.deadline)}</p>}</div>
          <div className="flex flex-wrap gap-2">{poll.status === 'open' && (poll.createdBy === currentUserProfile?.id || trip.permissions.canManageTrip) && <button type="button" onClick={() => void run(() => collaboration.closePoll(poll.id), 'Đã đóng bình chọn')} className="min-h-10 rounded-xl border border-outline-variant px-3 text-sm font-semibold">Đóng</button>}{poll.status === 'closed' && trip.permissions.canManageTrip && <button type="button" onClick={() => void run(() => collaboration.reopenPoll(poll.id), 'Đã mở lại bình chọn')} className="min-h-10 rounded-xl border border-outline-variant px-3 text-sm font-semibold">Mở lại</button>}{canDelete && <button type="button" onClick={async () => { if (await confirm({ title: 'Xóa bình chọn?', message: poll.question, confirmLabel: 'Xóa', tone: 'danger' })) await run(() => collaboration.deletePoll(poll.id), 'Đã xóa bình chọn'); }} className="min-h-10 rounded-xl border border-error px-3 text-sm font-semibold text-error">Xóa</button>}</div>
        </div>
        <div className="mt-4 space-y-2">{results.map(({ option, votes: optionVotes }) => <button key={option.id} type="button" disabled={!permissions.canVote || poll.status !== 'open' || expired} onClick={() => void run(() => collaboration.setPollVote(poll.id, option.id), 'Đã cập nhật phiếu')} className={`flex min-h-12 w-full items-center justify-between rounded-xl border px-4 text-left ${ownVotes.has(option.id) ? 'border-primary bg-primary/10' : 'border-outline-variant bg-surface'} disabled:cursor-not-allowed`}><span><strong className="text-sm">{option.label}</strong><span className="mt-0.5 block text-xs text-secondary">{optionVotes.map((vote) => trip.members.find((member) => member.id === vote.userId)?.displayName).filter(Boolean).join(', ') || 'Chưa có phiếu'}</span></span><span className="text-sm font-bold">{optionVotes.length}</span></button>)}</div>
        <CommentThread tripId={tripId} targetType="poll" targetId={poll.id} />
      </article>;
    })}{polls.length === 0 && <Empty icon={<Icons.BarChart3 className="size-8" />} title="Chưa có bình chọn" text="Tạo một câu hỏi để cả nhóm thống nhất nhanh hơn." />}</section>}

    {tab === 'notifications' && <section className="space-y-3">{notifications.map((notification) => <button key={notification.id} type="button" onClick={() => void collaboration.markNotificationRead(notification.id)} className={`w-full rounded-2xl border p-4 text-left ${notification.readAt ? 'border-outline-variant/50 bg-surface-container-lowest' : 'border-primary/40 bg-primary/5'}`}><div className="flex gap-3"><Icons.Bell className="mt-0.5 size-5 shrink-0 text-primary" /><div><p className="font-bold">{notification.title}</p>{notification.message && <p className="mt-1 text-sm text-secondary">{notification.message}</p>}<p className="mt-2 text-xs text-secondary">{formatLocalDateTime(notification.createdAt)}</p></div></div></button>)}{notifications.length === 0 && <Empty icon={<Icons.Bell className="size-8" />} title="Chưa có thông báo" text="Cập nhật về nhiệm vụ, bình luận và bình chọn sẽ xuất hiện tại đây." />}</section>}

    <Modal isOpen={isTaskOpen} onClose={() => setIsTaskOpen(false)} title="Thêm nhiệm vụ"><form onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (await run(() => collaboration.addTask({ tripId, title: String(data.get('title')), description: String(data.get('description') || ''), priority: data.get('priority') as 'low'|'normal'|'high', assigneeId: String(data.get('assigneeId') || '') || undefined, dueDate: String(data.get('dueDate') || '') || undefined, dueTime: String(data.get('dueTime') || '') || undefined, activityId: String(data.get('activityId') || '') || undefined, placeId: String(data.get('placeId') || '') || undefined }), 'Đã thêm nhiệm vụ')) setIsTaskOpen(false); }} className="space-y-4"><Field label="Tên nhiệm vụ"><input name="title" required maxLength={200} /></Field><Field label="Mô tả"><textarea name="description" rows={3} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Người phụ trách"><select name="assigneeId"><option value="">Chưa giao</option>{trip.members.map((member) => <option key={member.id} value={member.id}>{member.displayName}</option>)}</select></Field><Field label="Ưu tiên"><select name="priority" defaultValue="normal"><option value="low">Thấp</option><option value="normal">Bình thường</option><option value="high">Cao</option></select></Field><Field label="Hạn ngày"><input name="dueDate" type="date" /></Field><Field label="Hạn giờ"><input name="dueTime" type="time" /></Field><Field label="Hoạt động"><select name="activityId"><option value="">Không liên kết</option>{activities.filter((item) => item.tripId === tripId).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></Field><Field label="Địa điểm"><select name="placeId"><option value="">Không liên kết</option>{savedPlaces.filter((item) => item.tripId === tripId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div><button className="min-h-11 w-full rounded-xl bg-primary font-bold text-on-primary">Tạo nhiệm vụ</button></form></Modal>
    <Modal isOpen={Boolean(editingTask)} onClose={() => setEditingTask(undefined)} title="Sửa nhiệm vụ">{editingTask && <form onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (await run(() => collaboration.updateTask(editingTask.id, { title: String(data.get('title')), description: String(data.get('description') || ''), priority: data.get('priority') as 'low'|'normal'|'high', assigneeId: String(data.get('assigneeId') || ''), dueDate: String(data.get('dueDate') || ''), dueTime: String(data.get('dueTime') || ''), activityId: String(data.get('activityId') || ''), placeId: String(data.get('placeId') || '') }), 'Đã sửa nhiệm vụ')) setEditingTask(undefined); }} className="space-y-4"><Field label="Tên nhiệm vụ"><input name="title" required maxLength={200} defaultValue={editingTask.title} /></Field><Field label="Mô tả"><textarea name="description" rows={3} defaultValue={editingTask.description} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Người phụ trách"><select name="assigneeId" defaultValue={editingTask.assigneeId ?? ''}><option value="">Chưa giao</option>{trip.members.map((member) => <option key={member.id} value={member.id}>{member.displayName}</option>)}</select></Field><Field label="Ưu tiên"><select name="priority" defaultValue={editingTask.priority}><option value="low">Thấp</option><option value="normal">Bình thường</option><option value="high">Cao</option></select></Field><Field label="Hạn ngày"><input name="dueDate" type="date" defaultValue={editingTask.dueDate} /></Field><Field label="Hạn giờ"><input name="dueTime" type="time" defaultValue={editingTask.dueTime} /></Field><Field label="Hoạt động"><select name="activityId" defaultValue={editingTask.activityId ?? ''}><option value="">Không liên kết</option>{activities.filter((item) => item.tripId === tripId).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></Field><Field label="Địa điểm"><select name="placeId" defaultValue={editingTask.placeId ?? ''}><option value="">Không liên kết</option>{savedPlaces.filter((item) => item.tripId === tripId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div><button className="min-h-11 w-full rounded-xl bg-primary font-bold text-on-primary">Lưu nhiệm vụ</button></form>}</Modal>
    <Modal isOpen={isPollOpen} onClose={() => setIsPollOpen(false)} title="Tạo bình chọn"><form onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const optionLabels = String(data.get('options') || '').split('\n').map((value) => value.trim()).filter(Boolean); if (await run(() => collaboration.createPoll({ tripId, question: String(data.get('question')), kind: data.get('kind') as any, selectionMode: data.get('selectionMode') as any, deadline: String(data.get('deadline') || '') || undefined, options: optionLabels.map((label) => ({ label })) }), 'Đã tạo bình chọn')) setIsPollOpen(false); }} className="space-y-4"><Field label="Câu hỏi"><input name="question" required maxLength={300} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Loại"><select name="kind"><option value="custom">Tùy chỉnh</option><option value="place">Địa điểm</option><option value="hotel">Khách sạn</option><option value="restaurant">Nhà hàng</option><option value="time">Thời gian</option></select></Field><Field label="Cách chọn"><select name="selectionMode"><option value="single">Chọn một</option><option value="multiple">Chọn nhiều</option></select></Field></div><Field label="Các lựa chọn, mỗi dòng một mục"><textarea name="options" required rows={5} placeholder={'Lựa chọn 1\nLựa chọn 2'} /></Field><Field label="Hạn bình chọn"><input name="deadline" type="datetime-local" /></Field><button className="min-h-11 w-full rounded-xl bg-primary font-bold text-on-primary">Tạo bình chọn</button></form></Modal>
  </div>;
}

function TaskColumn({ status, tasks, ...props }: any) { return <section className="rounded-2xl bg-surface-container-low p-3"><h2 className="mb-3 px-1 font-headline font-bold">{{ todo: 'Cần làm', in_progress: 'Đang làm', done: 'Hoàn thành' }[status as TripTaskStatus]} · {tasks.length}</h2><div className="space-y-3">{tasks.map((task: any) => <TaskCard key={task.id} task={task} {...props} />)}</div></section>; }
function TaskCard({ task, trip, collaboration, currentUserId, run, confirm, onEditTask }: any) { const canEdit = collaboration.getPermissions(task.tripId).canCreateTasks; const canUpdate = canEdit || task.assigneeId === currentUserId && collaboration.getPermissions(task.tripId).canUpdateAssignedTasks; return <article className="rounded-2xl border border-outline-variant/50 bg-surface-container-lowest p-4"><div className="flex items-start justify-between gap-2"><div><span className={`text-xs font-bold ${task.priority === 'high' ? 'text-error' : 'text-secondary'}`}>{task.priority === 'high' ? 'Ưu tiên cao' : task.priority === 'low' ? 'Ưu tiên thấp' : 'Bình thường'}</span><h3 className="mt-1 font-headline text-lg font-bold">{task.title}</h3>{task.description && <p className="mt-1 text-sm text-secondary">{task.description}</p>}</div>{canEdit && <div className="flex"><button type="button" aria-label="Sửa nhiệm vụ" onClick={() => onEditTask(task)} className="p-2 text-secondary"><Icons.Edit2 className="size-4" /></button><button type="button" aria-label="Xóa nhiệm vụ" onClick={async () => { if (await confirm({ title: 'Xóa nhiệm vụ?', message: task.title, confirmLabel: 'Xóa', tone: 'danger' })) await run(() => collaboration.deleteTask(task.id), 'Đã xóa nhiệm vụ'); }} className="p-2 text-error"><Icons.Trash2 className="size-4" /></button></div>}</div><div className="mt-3 flex flex-wrap gap-2 text-xs text-secondary"><span>{trip.members.find((member: any) => member.id === task.assigneeId)?.displayName ?? 'Chưa giao'}</span>{task.dueDate && <span>· Hạn {task.dueDate}{task.dueTime ? ` ${task.dueTime}` : ''}</span>}</div>{canUpdate && <select value={task.status} onChange={(event) => void run(() => collaboration.updateTask(task.id, { status: event.target.value }), 'Đã cập nhật nhiệm vụ')} aria-label={`Trạng thái ${task.title}`} className="mt-3 min-h-10 w-full rounded-xl border border-outline-variant bg-surface px-3 text-sm"><option value="todo">Cần làm</option><option value="in_progress">Đang làm</option><option value="done">Hoàn thành</option></select>}<CommentThread tripId={task.tripId} targetType="task" targetId={task.id} /></article>; }
function Empty({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="rounded-2xl border border-dashed border-outline-variant p-8 text-center text-secondary"><span className="mx-auto block w-fit text-primary">{icon}</span><h2 className="mt-3 font-headline text-lg font-bold text-on-surface">{title}</h2><p className="mt-1 text-sm">{text}</p></div>; }
function Field({ label, children }: { label: string; children: React.ReactElement }) { return <label className="block text-sm font-bold"><span className="mb-1.5 block">{label}</span><span className="[&>*]:min-h-11 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:border-outline-variant [&>*]:bg-surface [&>*]:px-3">{children}</span></label>; }
